# Generated by Django 3.0.1 on 2019-12-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topnav',
            name='url',
            field=models.CharField(default='#', max_length=60),
        ),
    ]
