# Generated by Django 3.0.1 on 2020-01-02 07:12

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myeditor', '0002_topnav_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topnav',
            name='detail',
            field=models.CharField(blank=True, max_length=360, verbose_name='细节说明'),
        ),
        migrations.AddField(
            model_name='topnav',
            name='img',
            field=models.ImageField(blank=True, upload_to='assetinfo/', verbose_name='首页图片'),
        ),
        migrations.AddField(
            model_name='topnav',
            name='lang_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='topnav',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='导航栏名称'),
        ),
        migrations.AlterField(
            model_name='topnav',
            name='url',
            field=models.CharField(default='#', max_length=60, verbose_name='导航url'),
        ),
    ]
