# Generated by Django 3.0.1 on 2020-01-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeditor', '0004_auto_20200102_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='order_number',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=4),
        ),
    ]
